services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app_network

  web:
    image: ghcr.io/hrs-void/is-lab-app:latest
    container_name: web_app
    restart: always
    ports:
      - "127.0.0.1:8000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=master;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - app_network

volumes:
  mssql_data:

networks:
  app_network:
    driver: bridge
